apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deploy
spec:
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app-container
        image: clinkratcheat/cicd-app:50
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
